### ISSUE TITLE
Butterknife 8.4.0 does not work with Blade.

### ISSUE THREAD

**Issue by aartikov** [FrantisekGazo/Blade#17] opened 2016-12-23 04:42 UTC
I have simplest sample with Butterknife and Blade here https://github.com/aartikov/BladeTest
It crashes with NullPointerException because of Butterknife does not bind my views.

**Comment by FrantisekGazo** [comment] 2016-12-23 08:34
I'll try your project. 
But I use `ButterKnife` on my projects without a problem, so it most likely won't be problem with `Blade`.

**Comment by FrantisekGazo** [comment] 2016-12-24 13:15
@aartikov it looks like the problem is that `annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'` is used instead of `apt 'com.jakewharton:butterknife-compiler:8.4.0'` and the classes are not being generated by ButterKnife.

By default **Blade** adds the apt plugin, so maybe it causes the problem. I'll remove this dependency and publish a new release if it helps. I wanted to switch from `apt` to `annotationProcessor` so thanks for the issue ;) This way I'll do it sooner.

For now just use `apt 'com.jakewharton:butterknife-compiler:8.4.0'`.

**Comment by FrantisekGazo** [comment] 2016-12-26 18:20
@aartikov I released a new version - see [CHANGELOG](https://github.com/FrantisekGazo/Blade/blob/master/CHANGELOG.md)

With it you can use the `annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'`.

But please use config file, as described [here](https://github.com/FrantisekGazo/Blade/wiki#1-create-configuration-file).

**Comment by FrantisekGazo** [comment] 2016-12-26 18:48
I'm closing this issue.

@aartikov If you find anything else or just have a question please don't hesitate to open new issue 😉

**Closed by FrantisekGazo** 2016-12-26 18:48 UTC
